CREATE TABLE AuditLog
(
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    TABLE_NAME VARCHAR(50) NOT NULL,
    PRIM_KEY   BIGINT      NOT NULL,
    TIMESTAMP_ BIGINT      NOT NULL,
    EVENT_TYPE VARCHAR(20) NOT NULL,
    IS_NEW     BINARY DEFAULT 1
);

CREATE TABLE Wallet
(
    ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    AMOUNT DOUBLE       NOT NULL,
    NAME   VARCHAR(200) NOT NULL
);


CREATE TRIGGER WALLET_INS
    AFTER INSERT, UPDATE
    ON Wallet
    FOR EACH ROW
CALL "net.zoltancsaszi.actionmonitor.repository.MonitoringTrigger";
